### ISSUE TITLE
HTML is not escaped

### ISSUE THREAD

**Issue by helloworld** [AnmolMago/GithubTrending#2]
The descriptions (or repo names) are not escaped, so this extension is vulnerable to XSS. 

For example, this repo has `<input>` in its description: 

![image](https://cloud.githubusercontent.com/assets/3893054/16137156/a68542a4-33fe-11e6-8264-2723a5d2d84c.png)

And this is how it comes out:

![image](https://cloud.githubusercontent.com/assets/3893054/16137355/60a4596c-3400-11e6-9a0a-a1d0bbd9d4d1.png)

**Comment by AnmolMago** [comment]
Yeah, I noticed this as well, thanks! This will be fixed in the next update!

**Comment by helloworld** [comment]
:smile:
