### ISSUE TITLE
Remove Scrollbars

### ISSUE THREAD

**Issue by garyemerson** [AnmolMago/GithubTrending#3]
The single unscrollable page was much nicer and cleaner looking IMO. Additionally, the horizontal scrollbar is unnecessary bc it's never actually utilized even when the window is resized.

![image](https://cloud.githubusercontent.com/assets/5726308/16313372/c7f2c98c-392d-11e6-99c8-61b3ff84feeb.png)

**Comment by AnmolMago** [comment]
Hey, thanks for the information! I actually released 1.2.1 a couple of hours after removing these scrollbars but keeping the ability to scroll, could you confirm you got it by now?

**Comment by AnmolMago** [comment]
Hey @gmohammadioun, thanks for the information! I actually released 1.2.1 a couple of hours after removing these scrollbars but keeping the ability to scroll, could you confirm you got it by now?

**Comment by garyemerson** [comment]
Yep! The scrollbars are gone now.

One other related thought though, just from first glance it isn't obvious that there are more entries you can scroll down to. Some small element like a shadow would help. Sublime does this with horizontal scrolling:

![image](https://cloud.githubusercontent.com/assets/5726308/16345051/b37d8678-39f4-11e6-96a6-17482d1e0fca.png)

**Comment by AnmolMago** [comment]
Thats a great idea, thats for taking the time to input, will implement this in a future update!
