### ISSUE TITLE
Trending repos don't appear

### ISSUE THREAD

**Issue by talkahe** [AnmolMago/GithubTrending#5]
When I open a new tab the HTML page is loaded but repo info is empty.  Chrome console reports `Uncaught TypeError: Cannot use 'in' operator to search for 'results' in null` in my.js:89

![Screenshot](https://i.imgur.com/5zanO7y.png)

**Comment by AnmolMago** [comment]
I am looking into this now, thanks!

**Comment by AnmolMago** [comment]
It seemed Github a couple things which caused this to break, thanks for catching this!

It should be fixed now, hit "Force Refresh!" on the bottom left corner to see the changes right away!
